# Generated by Django 5.1.6 on 2025-02-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_SENA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedidos',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto_SENA.pedido'),
        ),
    ]
