# Generated by Django 5.1.6 on 2025-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_SENA', '0002_historialpedidos_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('bancolombia', 'Bancolombia'), ('nequi', 'Nequi'), ('daviplata', 'DaviPlata')], max_length=20),
        ),
    ]
