# Generated by Django 5.1.6 on 2025-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_SENA', '0003_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
    ]
