"""
Django settings for Sitio project.
Generated by 'django-admin startproject' using Django 5.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'mysite.com']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'social_django',
    'Proyecto_SENA',
]

JAZZMIN_SETTINGS = {
    # Títulos y encabezados
    "site_title": "Tienda LuiGui",
    "site_header": "Tienda LuiGui Admin",
    "site_brand": "Tienda LuiGui",
    "site_logo": None,  # Eliminamos el logo para usar solo texto
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": "images/favicon.png",
    
    # Textos de bienvenida
    "welcome_sign": "Bienvenido al Panel Administrativo",
    "copyright": "The Towers Development 2025",
    
    # Configuración del Avatar
    "user_avatar": None,
    
    # Menú superior - reducido para ahorrar espacio
    "topmenu_links": [
        {"name": "Sitio Web", "url": "/", "new_window": True},
        {"name": "Panel", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    
    # Menú lateral - más compacto
    "show_sidebar": True,
    "navigation_expanded": False,  # Colapsado por defecto
    
    # Iconos personalizados
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",
        "Proyecto_SENA": "fas fa-shopping-cart",
        "Proyecto_SENA.Contactos": "fas fa-address-book",
        "Proyecto_SENA.Inventarios": "fas fa-clipboard-list",
        "Proyecto_SENA.Pedidos": "fas fa-shopping-bag",
        "Proyecto_SENA.Perfil_usuarios": "fas fa-id-card",
        "Proyecto_SENA.Productos": "fas fa-box-open",
    },
    
    # Iconos por defecto
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
    
    # Configuración modal
    "related_modal_active": True,
    
    # Personalización UI
    "custom_css": """
        /* Reducir tamaños de botones y espaciado */
        .btn {
            padding: 0.25rem 0.5rem;
            font-size: 0.875rem;
        }
        
        /* Reducir espaciado en las tablas del panel */
        .table td, .table th {
            padding: 0.5rem;
        }
        
        /* Hacer el menú lateral más compacto */
        .nav-sidebar .nav-link {
            padding: 0.4rem 1rem;
        }
        
        /* Reducir el tamaño de los encabezados de las tarjetas */
        .card-header {
            padding: 0.5rem 1rem;
        }
        
        /* Reducir el espacio entre elementos */
        .card {
            margin-bottom: 0.75rem;
        }
        
        /* Hacer más compacto el menú lateral */
        .sidebar-dark-primary .nav-sidebar > .nav-item > .nav-link {
            font-size: 0.9rem;
        }
        
        /* Reducir tamaño de títulos */
        .card-title {
            font-size: 1rem;
            margin-bottom: 0;
        }
        
        /* Organizar actividades recientes en fila */
        .recent-actions-list {
            display: flex;
            flex-wrap: wrap;
        }
        .recent-actions-item {
            flex: 1 1 200px;
            max-width: 300px;
            margin: 5px;
        }
    """,
    "custom_js": None,
    
    # Formato del formulario de cambio
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Controles de UI
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,  # Desactivado para reducir distracciones
    
    # Enlaces rápidos en el dashboard
    "search_model": ["auth.User", "Proyecto_SENA.Productos"],
    
    # Botones de acción personalizados
    "actions_sticky": False,  # Desactivado para ahorrar espacio
    
    # Diseño del panel de control
    "order_with_respect_to": ["auth", "Proyecto_SENA", "Python Social Auth"],
}

# Mejora de la interfaz de usuario con tema oscuro/gris y más compacto
JAZZMIN_UI_TWEAKS = {
    # Tamaño del texto - reducido
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,
    
    # Colores y temas
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark bg-dark",
    "no_navbar_border": True,
    
    # Diseño general - más compacto
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    
    # Barra lateral - más compacta
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Tema principal
    "theme": "slate",
    "dark_mode_theme": None,
    
    # Clases para botones - tamaños más pequeños
    "button_classes": {
        "primary": "btn-sm btn-primary",
        "secondary": "btn-sm btn-secondary",
        "info": "btn-sm btn-info",
        "warning": "btn-sm btn-warning",
        "danger": "btn-sm btn-danger",
        "success": "btn-sm btn-success",
    },
}

# Mejora de la interfaz de usuario con tema oscuro/gris
JAZZMIN_UI_TWEAKS = {
    # Tamaño del texto
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Colores y temas - cambiado a oscuro/gris
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark bg-dark",
    "no_navbar_border": True,
    
    # Diseño general
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    
    # Barra lateral - cambiada a oscura
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Tema principal - cambiado a un tema más oscuro/gris
    "theme": "slate",  
    "dark_mode_theme": None,
    
    # Clases para botones
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Proyecto_SENA.middleware.PerfilCompletoMiddleware',
]

ROOT_URLCONF = 'Proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Proyecto_SENA/static'),
                    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY =  env("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

LOGIN_REDIRECT_URL = 'custom_login_redirect'

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'Proyecto_SENA.pipeline.verificar_perfil_completo',  
)